const moviesInitialList = [
  {
    title: 'Pelicula 1',
    director: 'Director 1',
    poster: 'http://poster1.ciemaec.com',
    time: 34,
    stills: ['http://still1.ciemaec.com', 'http://still2.ciemaec.com'],
    storyLine: 'esto es un story line de pelicula 1',
    trailer: 'http://trailer1.ciemaec.com',
    feactureFilm: 'Largometraje',
    genre: ['Documental'],
    year: 2017,
    country: 'Ecuador',
    language: ['Español'],
    subtitles: ['idioma1', 'idioma2'],
    target: 'Todo público',
    animation: false,
    expiration: null,
    festivals: ['festival 1', 'festival 2'],
    availableForREA: false,
    expiration: null,
    territoryLicense: ['nacional'],
  },
]

const newMovieObject = {
  title: 'Pelicula test',
  director: 'Director test',
  poster: 'http://poster2032.ciemaec.com',
  time: 34,
  stills: ['http://still1.ciemaec.com', 'http://still2.ciemaec.com'],
  storyLine: 'esto es un story line de pelicula 1',
  trailer: 'http://trailer35345.ciemaec.com',
  feactureFilm: 'Largometraje',
  genre: ['Documental'],
  year: 2017,
  country: 'Ecuador',
  language: ['Español'],
  subtitles: ['idioma1', 'idioma2'],
  target: 'Todo público',
  animation: false,
  expiration: null,
  festivals: ['festival 1', 'festival 2'],
  availableForREA: false,
}

module.exports = {
  moviesInitialList,
  newMovieObject,
}
