const moviesInitialList = [
  {
    title: 'Pelicula 1',
    director: 'Director 1',
    poster: 'http://poster1.ciemaec.com',
    time: 34,
    stills: ['http://still1.ciemaec.com', 'http://still2.ciemaec.com'],
    storyLine: 'esto es un story line de pelicula 1',
    trailer: 'http://trailer1.ciemaec.com',
    feactureFilm: 'Largometraje',
    genre: ['Documental'],
    year: 2017,
    country: 'Ecuador',
    language: ['Español'],
    subtitles: ['idioma1', 'idioma2'],
    target: 'Todo público',
    animation: false,
    festivals: ['festival 1', 'festival 2'],
    license: ['Nacional', 'Internacional'],
  },
  {
    title: 'Pelicula 2',
    director: 'Director 2',
    poster: 'http://poster2.ciemaec.com',
    time: 34,
    stills: ['http://still1.ciemaec.com', 'http://still2.ciemaec.com'],
    storyLine: 'esto es un story line de pelicula 2',
    trailer: 'http://trailer2.ciemaec.com',
    feactureFilm: 'Cortometraje',
    genre: ['Drama', 'Comedia'],
    year: 2020,
    country: 'Ecuador',
    language: ['Español', 'Ingles'],
    subtitles: ['idioma1'],
    target: '15 años',
    animation: false,
    festivals: ['festival 1'],
    license: ['Nacional', 'Retina Latina'],
  },
]

module.exports = {
  moviesInitialList,
}
